apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-data
  namespace: changedetection
  labels:
    app: changedetection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn