# changedetection-ingress.yml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: changedetection
  namespace: changedetection
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`changedetection.example.com`)
      kind: Rule
      services:
        - name: changedetection
          port: 80
  tls:
    secretName: changes-tls