apiVersion: v1
kind: Secret
metadata:
  name: changedetection-secret
  namespace: changedetection
  labels:
    app: changedetection
type: Opaque
data:
  API_KEY: Y2hhbmdlZGV0ZWN0aW9uLWFwaS1rZXk=
  NOTIFICATION_TOKEN: Y2hhbmdlZGV0ZWN0aW9uLW5vdGlmaWNhdGlvbi10b2tlbg==