apiVersion: v1
kind: ServiceAccount
metadata:
  name: changedetection-sa
  namespace: changedetection
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: changedetection-role
  namespace: changedetection
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: changedetection-rolebinding
  namespace: changedetection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: changedetection-role
subjects:
- kind: ServiceAccount
  name: changedetection-sa
  namespace: changedetection
