apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: changedetection
  name: changedetection-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi