apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ghost
  name: ghost-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"
  selector:
    matchLabels:
      usage: ghost-data