apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ghost
  name: ghost-pvc
  labels:
    app: ghost
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "5Gi"