apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ghost-netpolicy
  namespace: ghost
spec:
  podSelector:
    matchLabels:
      app: ghost
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from Traefik ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: traefik
    ports:
    - protocol: TCP
      port: 2368
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTP/HTTPS for external integrations, themes, etc.
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  # Allow SMTP for email notifications (port 25, 465, 587)
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 25
    - protocol: TCP
      port: 465
    - protocol: TCP
      port: 587
