apiVersion: v1
kind: Namespace
metadata:
  name: ghost
  labels:
    name: ghost
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted 