apiVersion: v1
kind: Secret
metadata:
  name: teslamate-secrets
  namespace: teslamate
type: Opaque
data:
  ENCRYPTION_KEY: #base64 encoded content
  DATABASE_PASS: #base64 encoded content
  POSTGRES_PASSWORD: #base64 encoded content