apiVersion: v1
kind: Service
metadata:
  name: littlelink
  namespace: littlelink
spec:
  ports:
  - name: littlelink
    port: 8080
    protocol: TCP
    targetPort: 3000
  selector:
    pod-label: littlelink