apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  ports:
  - port: 53
    protocol: UDP
  - port: 53
    protocol: TCP
  - port: 80
    protocol: TCP
  - port: 443
    protocol: TCP
  selector:
    app: pihole
  type: LoadBalancer