apiVersion: v1
kind: Secret
metadata:
  name: pihole-webpassword
  namespace: pihole
  labels:
    app: pihole
type: Opaque
data:
  # This is a more complex password encoded in base64
  # In production, use a properly generated strong password
  password: U3Ryb25nUGFzc3dvcmQxMjMh 