apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pihole-netpolicy
  namespace: pihole
spec:
  podSelector:
    matchLabels:
      app: pihole
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from Traefik ingress controller for web UI
  - from:
    - namespaceSelector:
        matchLabels:
          name: traefik
    ports:
    - protocol: TCP
      port: 80
  # Allow DNS queries from any namespace
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow DNS queries from external network (if used as network DNS)
  - ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  egress:
  # Allow DNS queries to upstream DNS servers
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTP/HTTPS for blocklist updates and gravity sync
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  # Allow all egress for DNS resolution
  - to:
    - podSelector: {}
