apiVersion: v1
kind: ServiceAccount
metadata:
  name: pihole-sa
  namespace: pihole
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pihole-role
  namespace: pihole
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pihole-rolebinding
  namespace: pihole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pihole-role
subjects:
- kind: ServiceAccount
  name: pihole-sa
  namespace: pihole
