apiVersion: v1
kind: Service
metadata:
  name: pihole-service
spec:
  selector:
    app: pihole
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: dns
    protocol: UDP
    port: 53
    targetPort: 53