apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-server
  labels:
    app: teamcity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
      - name: teamcity-server
        image: jetbrains/teamcity-server
        ports:
        - containerPort: 8111
          name: http
        env:
        - name: TEAMCITY_SERVER_MEM_OPTS
          value: "-Xmx1024m -XX:MaxMetaspaceSize=250m"
        volumeMounts:
        - name: teamcity-data
          mountPath: /data/teamcity_server/datadir
      volumes:
      - name: teamcity-data
        persistentVolumeClaim:
          claimName: teamcity-data-claim
