apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamcity-server
  template:
    metadata:
      labels:
        app: teamcity-server
    spec:
      containers:
      - name: teamcity-server
        image: jetbrains/teamcity-server:latest
        ports:
        - containerPort: 8111
        volumeMounts:
        - name: teamcity-server-data
          mountPath: /data/teamcity_server/datadir
      volumes:
      - name: teamcity-server-data
        persistentVolumeClaim:
          claimName: teamcity-server-pvc
