apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
      containers:
      - name: teamcity-agent
        image: jetbrains/teamcity-agent:latest
        env:
        - name: SERVER_URL
          value: http://teamcity-server:8111
        volumeMounts:
        - name: teamcity-agent-config
          mountPath: /data/teamcity_agent/conf
        - name: teamcity-agent-logs
          mountPath: /data/teamcity_agent/logs
        - name: teamcity-agent-temp
          mountPath: /data/teamcity_agent/temp
      volumes:
      - name: teamcity-agent-config
        emptyDir: {}
      - name: teamcity-agent-logs
        emptyDir: {}
      - name: teamcity-agent-temp
        emptyDir: {}
