apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo
  namespace: default
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.yourdomain.com`)
      kind: Rule
      services:
        - name: demo
          port: 80
      middlewares:
        - name: default-headers
          namespace: default
    - match: Host(`yourdomain.com`)
      kind: Rule
      services:
        - name: demo
          port: 80
      middlewares:
        - name: default-headers
          namespace: default
  tls:
    certResolver: le