apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo
  namespace: demo
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`demo.yourdomain.com`)
      kind: Rule
      services:
        - name: demo-service
          port: 80
      middlewares:
        - name: default-headers
          namespace: default
  tls:
    certResolver: le