apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nextcloud-app-netpolicy
  namespace: nextcloud
spec:
  podSelector:
    matchLabels:
      app: nextcloud-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from Traefik ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: traefik
    ports:
    - protocol: TCP
      port: 80
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow connections to MySQL database
  - to:
    - podSelector:
        matchLabels:
          app: nextcloud-db
    ports:
    - protocol: TCP
      port: 3306
  # Allow connections to external MySQL if needed
  - to:
    - namespaceSelector:
        matchLabels:
          name: mysql
    ports:
    - protocol: TCP
      port: 3306
  # Allow HTTP/HTTPS for external storage, federation, app store
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  # Allow SMTP for email notifications
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 25
    - protocol: TCP
      port: 465
    - protocol: TCP
      port: 587
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nextcloud-db-netpolicy
  namespace: nextcloud
spec:
  podSelector:
    matchLabels:
      app: nextcloud-db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow connections from Nextcloud app
  - from:
    - podSelector:
        matchLabels:
          app: nextcloud-app
    ports:
    - protocol: TCP
      port: 3306
  egress:
  # Allow DNS resolution
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Database doesn't need other egress
