apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db-password
  namespace: nextcloud
  labels:
    app: nextcloud
type: Opaque
data:
  # Base64 encoded values - in production use a proper secret management system
  password: VzNsY29tZVRvTmV4dGNsb3VkMjAyNCE=
  root-password: UjAwdFBAc3N3MHJkTjN4dGNsb3VkMjAyNCE=
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-admin-credentials
  namespace: nextcloud
  labels:
    app: nextcloud
type: Opaque
data:
  # Base64 encoded values - in production use a proper secret management system
  username: YWRtaW4=
  password: TmV4dGNsb3VkQGRtaW5QYXNzdzByZDIwMjQh
