apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homarr-claim0
  namespace: homarr
  labels:
    app: homarr
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi