apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: uptime
  name: uptime
  namespace: uptime
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi