apiVersion: v1
kind: Service
metadata:
  name: uptime-svc
  namespace: uptime
  labels:
    app: uptime
    role: monitoring
spec:
  type: ClusterIP
  selector:
    app: uptime
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3001