apiVersion: apps/v1
kind: Deployment
metadata:
  name: smokeping
  namespace: smokeping
  labels:
    app: smokeping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smokeping
  template:
    metadata:
      labels:
        app: smokeping
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: smokeping
        image: linuxserver/smokeping:latest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /smokeping/smokeping.cgi
            port: http
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /smokeping/smokeping.cgi
            port: http
          initialDelaySeconds: 45
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        volumeMounts:
        - name: smokeping-pvc
          mountPath: /data
        - name: smokeping-config
          mountPath: /config/Targets
          subPath: Targets
      volumes:
        - name: smokeping-pvc
          persistentVolumeClaim:
            claimName: smokeping-pvc
        - name: smokeping-config
          configMap:
            name: smokeping-config