apiVersion: v1
kind: ConfigMap
metadata:
  name: smokeping-config
  namespace: smokeping
  labels:
    app: smokeping
data:
  Targets: |
    *** Targets ***

    probe = FPing

    menu = Top
    title = Network Latency Grapher
    remark = Welcome to the SmokePing website. Here you will learn about the latency of our network.

    + Local

    menu = Local
    title = Local Network
    remark = This section contains local network hosts

    ++ LocalMachine

    menu = Local Machine
    title = This host
    host = localhost

    + Internet

    menu = Internet
    title = Internet Connectivity
    remark = This section contains Internet targets

    ++ GoogleDNS

    menu = Google DNS
    title = Google DNS Servers
    remark = Google's public DNS servers

    +++ GoogleDNS1
    menu = Google DNS 1
    title = Google DNS 8.8.8.8
    host = 8.8.8.8

    +++ GoogleDNS2
    menu = Google DNS 2
    title = Google DNS 8.8.4.4
    host = 8.8.4.4

    ++ CloudflareDNS

    menu = Cloudflare DNS
    title = Cloudflare DNS Servers
    remark = Cloudflare's public DNS servers

    +++ CloudflareDNS1
    menu = Cloudflare DNS 1
    title = Cloudflare DNS 1.1.1.1
    host = 1.1.1.1

    +++ CloudflareDNS2
    menu = Cloudflare DNS 2
    title = Cloudflare DNS 1.0.0.1
    host = 1.0.0.1

    ++ Websites

    menu = Popular Websites
    title = Popular Websites

    +++ Google
    menu = Google
    title = Google Website
    host = google.com

    +++ GitHub
    menu = GitHub
    title = GitHub Website
    host = github.com 