apiVersion: v1
kind: Service
metadata:
  name: smokeping-svc
  namespace: smokeping
spec:
  selector:
    app: smokeping
  ports:
  - name: smokeping
    port: 80
    protocol: TCP
    targetPort: 80