apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smokeping-pvc
  namespace: smokeping
  labels:
    app: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi