apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: smokeping
  name: smokeping-pvc1
  namespace: smokeping
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi