apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-name
  labels:
    app.kubernetes.io/name: app-name
spec:
  project: default
  source:
    repoURL: https://github.com/user/repo.git
    path: manifests/
    targetRevision: HEAD
    helm:
      values:
        - path: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
