apiVersion: v1
kind: Secret
metadata:
  name: adguard-secret
  namespace: adguard
  labels:
    app: adguard
    app.kubernetes.io/name: adguard
    app.kubernetes.io/instance: adguard
type: Opaque
data:
  users.yaml: BASE64_ENCODED_USERS_CONFIG  # Replace with actual base64 encoded users config