apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: adguard-home-netpolicy
  namespace: adguard
spec:
  podSelector:
    matchLabels:
      app: adguard-home
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from Traefik ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: traefik
    ports:
    - protocol: TCP
      port: 80
  # Allow DNS queries (if AdGuard is used as DNS server)
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  egress:
  # Allow DNS queries to external DNS servers
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTP/HTTPS to internet for blocklist updates
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  # Allow all traffic to internet IPs (for DNS resolution and blocklist updates)
  - to:
    - podSelector: {}
