apiVersion: v1
kind: Service
metadata:
  name: firefox-service
  labels:
    app: firefox
spec:
  type: LoadBalancer
  ports:
  - port: 5900
    targetPort: 5900
    protocol: TCP
  selector:
    app: firefox
