apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: mysql
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-role
  namespace: mysql
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-rolebinding
  namespace: mysql
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mysql-role
subjects:
- kind: ServiceAccount
  name: mysql-sa
  namespace: mysql
