apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:  
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-password
                key: password
        ports:
        - containerPort: 3306
          name: mysql
        securityContext:
          runAsUser: 104
          runAsGroup: 113
          fsGroup: 113
