apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
  namespace: mysql
  labels:
    app: mysql
type: Opaque
data:
  # This is "MySQLStrongPassword123!" base64 encoded
  # In production, use a proper secret management solution
  password: TXlTUUxTdHJvbmdQYXNzd29yZDEyMyE=