apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-netpolicy
  namespace: mysql
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: nextcloud
    - namespaceSelector:
        matchLabels:
          name: mysql-workbench
    ports:
    - protocol: TCP
      port: 3306
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
