apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: littlelink
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`about.example.com`)
      kind: Rule
      services:
        - name: littlelink
          port: 8080