apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-workbench-pvc
  namespace: mysql-workbench
  labels:
    app: mysql-workbench
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn 