apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: startpage
  name: startpage-pvc
  namespace: startpage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
# Thanks to loganmarchione for creating and maintaining this image: https://hub.docker.com/r/loganmarchione/docker-php-startpage