apiVersion: v1
kind: Service
metadata:
  name: startpage
  namespace: startpage
spec:
  ports:
  - name: startpage
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    pod-label: startpage
# Thanks to loganmarchione for creating and maintaining this image: https://hub.docker.com/r/loganmarchione/docker-php-startpage